# Generated by Django 5.2.15 on 2026-10-10 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicle', '0006_journal_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chronicleentry',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Private journal and grade entries are readable only by their author. The author can explicitly share an entry with family.'),
        ),
        migrations.AlterField(
            model_name='chronicleentry',
            name='kind',
            field=models.CharField(choices=[('birthday', 'Birthday'), ('chapter_start', 'Chapter start'), ('chapter_end', 'Chapter end'), ('first_ever', 'First ever'), ('milestone', 'Milestone'), ('recap', 'Recap'), ('manual', 'Manual'), ('journal', 'Journal'), ('creation', 'Creation'), ('grade', 'Grade')], max_length=32),
        ),
        migrations.CreateModel(
            name='GradeDailyCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_on', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'occurred_on'], name='chronicle_g_user_id_a19b2d_idx')],
                'unique_together': {('user', 'occurred_on')},
            },
        ),
    ]
