#!/usr/bin/env python
"""Copy the shared art/palette to React and Unity; --check detects drift.

Canonical PNGs are production exports, not purchased model/source packages.
Replacing those exports changes presentation without changing receipt IDs.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import shutil


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "shared/storybook"


def destinations() -> list[tuple[Path, Path]]:
    manifest = SOURCE / "presentation.json"
    presentation = json.loads(manifest.read_text(encoding="utf-8"))
    if presentation["schema_version"] != 1:
        raise ValueError("Unsupported storybook presentation version")
    companion = presentation["companion"]
    filenames = {companion[key] for key in ("portrait", "happy_portrait", "blink_portrait")}
    filenames.update(item["image"] for item in presentation["keepsakes"])
    pairs = [
        (manifest, ROOT / "frontend/src/storybook/presentation.json"),
        (manifest, ROOT / "unity/AbbyCamp/Assets/AbbyCamp/Resources/StorybookPresentation.json"),
    ]
    font_name = presentation["typography"]["font"]
    if Path(font_name).name != font_name or not font_name.endswith(".ttf"):
        raise ValueError("The shared font must be a local TTF filename")
    for filename in (font_name, "OFL.txt"):
        source = SOURCE / "fonts" / filename
        pairs.extend([
            (source, ROOT / "frontend/src/storybook/assets" / filename),
            (source, ROOT / "unity/AbbyCamp/Assets/AbbyCamp/Art/Shared" / filename),
            (source, ROOT / "unity/AbbyCamp/Assets/WebGLTemplates/AbbyPhone/TemplateData" / filename),
        ])
    for filename in sorted(filenames):
        if Path(filename).name != filename or not filename.endswith(".png"):
            raise ValueError("Artwork must be a local PNG filename")
        source = SOURCE / "art" / filename
        if not source.is_file():
            raise FileNotFoundError(source)
        pairs.extend([
            (source, ROOT / "frontend/src/storybook/assets" / filename),
            (source, ROOT / "unity/AbbyCamp/Assets/AbbyCamp/Art/Shared" / filename),
        ])
    return pairs


def web_theme() -> tuple[Path, str]:
    presentation = json.loads((SOURCE / "presentation.json").read_text(encoding="utf-8"))
    palette = presentation["palette"]
    font = presentation["typography"]["font"]
    css = f'''/* Generated by scripts/storybook/sync_presentation.py. */
@font-face {{ font-family: "Abby Nunito"; src: url("{font}") format("truetype"); font-weight: 600; font-style: normal; font-display: swap; }}
:root {{ font-family: "Abby Nunito", sans-serif; color: {palette["ink"]}; background: {palette["sky"]}; }}
#unity-canvas {{ background: {palette["sky"]}; }}
.overlay {{ background: radial-gradient(ellipse at 15% 10%, {palette["mint"]}, transparent 55%), {palette["paper"]}; }}
.card button {{ color: {palette["paper"]}; background: {palette["primary"]}; border-radius: 26px; }}
.card button:focus-visible, a:focus-visible {{ outline-color: {palette["primary"]}; }}
a {{ color: {palette["ink"]}; }}
progress {{ accent-color: {palette["primary"]}; }}
'''
    return ROOT / "unity/AbbyCamp/Assets/WebGLTemplates/AbbyPhone/TemplateData/storybook.css", css


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify copies without writing")
    args = parser.parse_args()
    mismatches = []
    pairs = destinations()
    for source, target in pairs:
        if args.check:
            if not target.is_file() or source.read_bytes() != target.read_bytes():
                mismatches.append(str(target.relative_to(ROOT)))
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source, target)
    theme_target, theme_css = web_theme()
    if args.check:
        if not theme_target.is_file() or theme_target.read_text(encoding="utf-8") != theme_css:
            mismatches.append(str(theme_target.relative_to(ROOT)))
    else:
        theme_target.parent.mkdir(parents=True, exist_ok=True)
        theme_target.write_text(theme_css, encoding="utf-8")
    if mismatches:
        parser.exit(1, "Storybook copies differ; run scripts/storybook/sync_presentation.py:\n" + "\n".join(mismatches) + "\n")
    parser.exit(0, f"Storybook presentation {'verified' if args.check else 'synced'} ({len(pairs) + 1} files).\n")


if __name__ == "__main__":
    main()
